### ISSUE TITLE
Tests failing due to Rack 2.0 not supporting Ruby < 2.2.2

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#100]
See: https://travis-ci.org/tinfoil/devise-two-factor/jobs/149565884

This can be fixed in a few ways:
- Locking the version of Rack to 1.x
- Dropping support for Ruby 2.1.x and upgrading 2.2.0 tests to 2.2.2 or above
- Using appraisals to use different gemfiles depending on the Ruby/Rails version.

**Comment by sidcool1234** [comment]
Is the latest build stable enough to be used in projects?  Any failing/security issues?

**Comment by connorshea** [comment]
@sidcool1234 it should be yes

**Comment by sidcool1234** [comment]
Thanks @connorshea .  Appreciate your quick reply.
