### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by archonic** [tinfoil/devise-two-factor#101]
Getting `undefined method 'for' for #<Devise::ParameterSanitizer:0x007fbfb5a59ed0>`
in
`app/controllers/application_controller.rb:11:in 'configure_permitted_parameters'`

**Comment by micheleps** [comment]
@archonic  go to application_controller.rb and change the following

```
-    devise_parameter_sanitizer.for(:sign_in) << :otp_attempt
+    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
```

Later i will pull request it

**Comment by mieps** [comment]
@archonic  go to application_controller.rb and change the following

```
-    devise_parameter_sanitizer.for(:sign_in) << :otp_attempt
+    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
```

Later i will pull request it

**Comment by diegorv** [comment]
Fixed here: https://github.com/tinfoil/devise-two-factor/pull/102
