### ISSUE TITLE
NoMethodError: undefined method `otp_backup_codes' 

### ISSUE THREAD

**Issue by jonhue** [tinfoil/devise-two-factor#104]
I've just installed this gem and this is the error I get on log in:

> NoMethodError in Devise::SessionsController#create
undefined method `otp_backup_codes' for #\<User:0xd55b920\>

I added Backup Codes.
I also have not called any specific methods yet.

**Comment by bsedat** [comment]
Did you add the `:two_factor_authenticatable` option to the devise line in your `User` class? You'll also need to generate and run migrations to add the required columns to your database.

**Comment by jonhue** [comment]
I did all that. One thing I was not sure though, what is the key I should enter for the ENV Variable?

**Comment by bsedat** [comment]
It should be a key akin to your devise secret key. Likely you want to run `SecureRandom.hex(64)` and save that value to an environment variable.

Is there a way you can provide an example application to reproduce the error you are getting? We have a [demo application](https://github.com/tinfoil/devise-two-factor/tree/master/demo) that might provide some insight on integrating devise-two-factor into a rails project.

**Comment by jonhue** [comment]
Ok, I noticed that I in my inexcusable stupidity forgot to add the required column `otp_backup_codes` to the database.
