### ISSUE TITLE
How to generate manual key for Google Authenticator?

### ISSUE THREAD

**Issue by generationloss** [tinfoil/devise-two-factor#123]
Google Authenticator provides the option to manually enter a 16-digit key as opposed to scanning the QR code.  The "secret" field in the provisioning uri is much longer than 16 digits, so that's not it...I've spent hours Googling and pawing through source code and can't find an answer to this seemingly straightforward question - hoping you can be of help.

**Comment by bsedat** [comment]
It seems like Google Authenticator has some strong opinions on key length. Currently our default key length is 192 bits as changed [here](https://github.com/tinfoil/devise-two-factor/commit/08f13fcf79b62fb06468d55b3ecae2503d604e56). You can go ahead and configure devise_two_factor in your model to have a shorter key length if needed (like for Google Authenticator's manual entry), at the cost of making it slightly easier for someone to crack - note that the key length is the number of bytes so multiply by 8 to get the desired number of bits.

**Comment by bsedat** [comment]
Some more background is also [on this Stackoverflow answer](https://security.stackexchange.com/questions/45053/why-does-google-cripple-the-2fa-google-authenticator-pam-module).

**Comment by generationloss** [comment]
Thanks very much for the prompt and helpful reply!  Very strange that Google would opt for such a relatively low-security implementation, but very relieved to finally have this figured out.

**Comment by bsedat** [comment]
No problem and thanks for the good question! I'm closing this for now but let us know if there's anything else you need.
