### ISSUE TITLE
Allow newer rotp

### ISSUE THREAD

**Issue by darix** [tinfoil/devise-two-factor#124]
Any specific reasons why this is locked down to 2.x?

**Comment by catpham** [comment]
@borski @bsedat @ShaneWilton 👋 any idea when/if newer ropt versions will be allowed?

**Comment by weiyunlu** [comment]
If anyone is still looking for this, I have a fork that updates rotp to >= 5.0
https://github.com/zetatango/devise-two-factor/

**Comment by murb** [comment]
This seems to be resolved by now: https://github.com/tinfoil/devise-two-factor/blob/main/devise-two-factor.gemspec#L28
