### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by ce07c3** [tinfoil/devise-two-factor#125]
> 3) Stores the hashed backup codes in the database

Where does it actually save?

```rb
def generate_otp_backup_codes!
  codes           = []
  number_of_codes = self.class.otp_number_of_backup_codes
  code_length     = self.class.otp_backup_code_length

  number_of_codes.times do
    codes << SecureRandom.hex(code_length / 2) # Hexstring has length 2*n
  end

  hashed_codes = codes.map { |code| Devise::Encryptor.digest(self.class, code) }
  self.otp_backup_codes = hashed_codes

  codes
end
```

http://www.rubydoc.info/gems/devise-two-factor/2.2.1/Devise/Models/TwoFactorBackupable#invalidate_otp_backup_code!-instance_method

**Comment by bsedat** [comment]
Ah yeah, that sounds like a confusing piece of the documentation. We're storing the backup codes in the model but those updates haven't been persisted to the database (yet).

**Comment by ce07c3** [comment]
I’ll create a PR. :)

**Comment by neymarsabin** [comment]
@ce07c3 any update on this? Looks like it still does not save hashed codes in the database.

**Comment by ce07c3** [comment]
This gem is a bit old, don't know if it makes sense.
