### ISSUE TITLE
Does not support other encryption schemes using :encryptable

### ISSUE THREAD

**Issue by lancecarlson** [tinfoil/devise-two-factor#129]
Try using this plugin with:

https://github.com/plataformatec/devise-encryptable

and something like:

https://github.com/erdostom/devise-argon2

and it tries to use the default bcrypt and not argon2.

**Comment by lancecarlson** [comment]
@bsedat right. I'm not referring to the attr_encrypted stuff. That stuff is completely separate and fine. The problem is when you try to use encryptable for password authentication (when a user is otp_required_for_login = false. It tries to login using bcrypt by default instead of argon2. Does that make sense?

**Comment by bsedat** [comment]
Ah, I understand the problem now. Both libraries are patching into the DatabaseAuthenticatable process so there's likely an incompatibility there. We'd have to look into how DeviseEncryptable works.

**Comment by lancecarlson** [comment]
It's kind of awkward that devise puts the password encryptor decision in a separate plugin. I feels like this should be a first class API that you can override. </rant> :)

**Comment by ArchieJG** [comment]
@lancecarlson @borski So is this gem incompatible with devise-encryptable?

**Comment by lancecarlson** [comment]
@ArchieJG correct

**Comment by steakknife** [comment]
Long ago, we tried to get devise-encryptable to work with devise-scrypt. I reported it and Valim offered only some dismissive BS about other priorities. Went with a donkey punch patch instead. Devise lacks a middleware system and professionalism.

**Comment by lancecarlson** [comment]
sad :(
