### ISSUE TITLE
key must be 32 bytes or longer

### ISSUE THREAD

**Issue by Alagaesia93** [tinfoil/devise-two-factor#137]
Hello,

I'm using ruby 2.5.1 and Rails 5.2.1.

When I do 
`current_user.otp_secret = User.generate_otp_secret`

I have this error
`ArgumentError (key must be 32 bytes or longer)`

What am I supposed to do?

**Comment by AlbaHoo** [comment]
@Alagaesia93 I believe you have to set whatever key you used in your ENV with length > 32 bytes,
in the example from README.md, which is the key `YOUR_ENCRYPTION_KEY_HERE`
`devise :two_factor_authenticatable,
         :otp_secret_encryption_key => ENV['YOUR_ENCRYPTION_KEY_HERE']`

I think it's a rails 5 thing, and it should be specified in the documentation somewhere.

**Comment by Alagaesia93** [comment]
Thank you @AlbaHoo, you solved my issue. The generated key, which should be set by the initializer IMHO, has to be 32 bytes.
