### ISSUE TITLE
NoMethodError `verify_with_drift' for ROTP::TOTP 

### ISSUE THREAD

**Issue by akshaysharma096** [tinfoil/devise-two-factor#140]
In case of generating a new otp secret for the following error is shown, seems to be a compatibility issue.

**Comment by mentero** [comment]
You need to lock on ROTP v2.0. Same thing happened to me.

**Comment by alexlev1** [comment]
Also, you can use my gem fork with newer rotp gem version (4.0.0): [https://github.com/alexlev1/devise-two-factor](https://github.com/alexlev1/devise-two-factor)
