### ISSUE TITLE
setting the otp_secret fails with ruby 2.6

### ISSUE THREAD

**Issue by krtschmr** [tinfoil/devise-two-factor#142]
`u.otp_secret = User.generate_otp_secret`

ArgumentError: key must be 32 bytes or longer
from /home/tim/.rvm/gems/ruby-2.6.0/gems/encryptor-3.0.0/lib/encryptor.rb:60:in `crypt'

**Comment by krtschmr** [comment]
dunno, know it's working. weired.

**Comment by rafa-sr** [comment]
Hello I am having the same issue how do you solve it?

**Comment by krtschmr** [comment]
@rafa-sr  some key length is wrong. needs a longer key.
