### ISSUE TITLE
clean_up_passwords is over-written by two_factor_authenticatable.rb

### ISSUE THREAD

**Issue by seanders** [tinfoil/devise-two-factor#152]
It seems like `models/two_factor_authenticatable.rb` is overwriting the `#clean_up_passwords` method as defined by devise in 

https://github.com/tinfoil/devise-two-factor/blob/5549aba9f73827c1b8e925f10f6a518e5b10aaf4/lib/devise_two_factor/models/two_factor_authenticatable.rb#L58-L60

is overwriting

https://github.com/plataformatec/devise/blob/e91b8ee0bac0503af119bf7333499d7729166a4d/lib/devise/models/database_authenticatable.rb#L72-L74

Im thinking a simple `super` in `two_factory_authenticatable.rb` would fix this?

**Comment by ebeeson** [comment]
Fix merged and will be included in the forthcoming release.
