### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by jonathansimmons** [tinfoil/devise-two-factor#170]
We're looking to incorporate this gem into our app but before doing so I'm trying to sort out how maintained it is, or will continue to be?

I'm so grateful it exists as a starting place. We're happy to simply fork it build but could potentially contribute ourselves. All of this stems from what appears to be a bit of silence on issues and some very stale PR's.

I just wanted to check in on the active maintenance of the gem and see where @tinfoil stand on it. 

cc @bsedat

**Comment by kevinhq** [comment]
I wonder about this too. We have many strange validation errors suddenly - after we incorporate this gem into our app. 

When we remove it, all validation errors are gone and all tests passed again.

Our app is running on:

- Rails 6.0.2.2
- Ruby 2.6.5

**Comment by sjieg** [comment]
@bsedat @borski @QuinnWilton would love to hear your input on this. Any chance there could be a handover or include new maintainers as you guys have possibly moved on from Tinfoil?

Great work on the project by the way, seeing it's still very relevant. Even GitLab is using this as 2FA tool 🎉

**Comment by borski** [comment]
Please see my comment here: https://github.com/tinfoil/devise-two-factor/issues/183#issuecomment-765622740

I promise we're working on figuring this out! :)

**Comment by borski** [comment]
We are now able to maintain this project (and others) again. We are considering, in the future, finding a co-maintainer, but no details on that yet; will provide more info as we figure that out! In the meantime, closing this issue as resolved.
