### ISSUE TITLE
Configure OTP Drift value according to strategies

### ISSUE THREAD

**Issue by neymarsabin** [tinfoil/devise-two-factor#175]
I have done pretty much everything to setup this alongside devise_token_auth in my Rails API application. I have a case where users are allowed to choose between multiple strategies like sms, email or google authenticator. The problem is this gem allows only one configuration for OTP interval/drift value which is default to 30s. This works for google authenticator but for email and sms I want to configure it to around 2m:30s. Is there any way I can achieve this?

**Comment by neymarsabin** [comment]
There is an option to configure otp_allowed_drift from devise config. 
In `config/intializers/devise.rb`: 
```
# acceptance interval in seconds between one-time secret codes
Devise.otp_allowed_drift = 1800
```
This is the core configuration to accept/reject otp codes. I implemented strategies on my own. One challenge was invalidating otp code when user hit resend. For that I implemented something like this: 

```
  .... 
  def send_email
    generate_secret if @user.otp_method == User::OTP_METHODS[:email]
    @user.send_twofa_email
  end
   
  private

  def generate_secret
    @user.otp_secret = User.generate_otp_secret
    @user.save!
  end
```

Hope this helps someone. Closing the issue.

**Comment by jvlara** [comment]
Hi. this was the thing i was looking for, thanks!

**Comment by bettysteger** [comment]
@neymarsabin can you please give me an example how it works with [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth/) ? 🙏🏻

i have set-up both gems correctly, but when i enable 2fa for 1 user, i can still login with email and password.
how can i prevent the login when 2fa is enabled?

**Comment by neymarsabin** [comment]
@bettysteger you will need to override your sessions action to check if the user has OTP enabled or not? If it's enabled then you need to expect some parameter from the client that contains the OTP code. So, whenever OTP is enabled and OTP code in params is present and OTP code is valid then you will send correct headers to the client.

`
user.otp_required_for_login? && user.validate_mfa_login(params[:otp_attempt])
` 
You can use the `validate_and_consume_otp!(otp_attempt)` method from the gem to validate otp attempt. I can share you the full implementation in PM.

**Comment by bettysteger** [comment]
If anyone needs this, i created a [gist](https://gist.github.com/bettysteger/670a9a3ef0814ff52059dc2e6757e580)
