### ISSUE TITLE
Backup codes + mysql

### ISSUE THREAD

**Issue by feens** [tinfoil/devise-two-factor#18]
Just a note that in it's current form, using backup codes with the mysql db driver won't work, as mysql doesn't support the array data type.  Rails will save the codes w/o issue, but the code fails when trying to read the field as it is a serialized YAML string.  I had to use this in my User model to make it work:

  def otp_backup_codes
    codes = self.read_attribute(:otp_backup_codes)
    codes = YAML::load(codes) unless codes.kind_of?(Array) || codes.nil?
    codes
  end

Additionally, Devise has moved their Devise.bcrypt definition into the database_authenticatable module, so I had to use a monkey-patch to define it myself.

**Comment by common-nighthawk** [comment]
thank you, @feens!  this helped me a lot today.

also--i ran into another problem using backup codes with mysql.  i kept hitting the following error "Mysql2::Error: Data too long for column".

i was able to fix it without much trouble by changing the column type--
add_column :users, :otp_backup_codes, :text, array: true

if someone wants me to open a separate issue, just let me know.
