### ISSUE TITLE
Lack of compatibility with Rails 6.1?

### ISSUE THREAD

**Issue by mensfeld** [tinfoil/devise-two-factor#183]
Hey there,

First of all, thank you for this amazing library.

I tried checking the changelog, but it seems a bit outdated.

Is there a reason, why this lib got locked down to 6.0 from potentially 6.1? I've been running it without problems with 6.1.

3.0.0 could resolve to 6.1 but further cannot.

ref https://my.diffend.io/gems/devise-two-factor/3.0.0/3.1.0#d2h-305102

**Comment by dominiceden** [comment]
Looks like there is a PR kindly provided by @jason-hobbs here: #184 - just waiting for a maintainer to merge it as it's quite a simple change of updating dependency versions.

**Comment by sjieg** [comment]
The PR has been updated: #185
For anyone looking, you can update your Gemfile with:
```Ruby
gem 'devise-two-factor', git: 'https://github.com/jason-hobbs/devise-two-factor.git', ref: '37ca8a1' # Rails 6.1 compatibility: https://github.com/tinfoil/devise-two-factor/issues/183
```
@jason-hobbs thanks! If you'd merge the code on your fork to master, I'd be happy to point to the branch instead of the ref.

**Comment by jason-hobbs** [comment]
I have merged to master on my fork.

**Comment by mensfeld** [comment]
@jason-hobbs thank you. Any chance for a release?

**Comment by santib** [comment]
+1 Can we please get a release that supports Rails 6.1? cc @bsedat @borski @QuinnWilton 🙏

**Comment by borski** [comment]
Hey all - really sorry for the radio silence and delay here. This is an active concern for us, but we just got acquired a year ago (January 2020) by Synopsys and are figuring out their procedures for OSS, from a legal perspective. Please bear with us just a bit longer as we figure the right solution out and/or get the right approvals to keep this maintained. 

Really appreciate all your patience, and again, I'm so sorry for the delay in responding. It has been...hectic here. :)

**Comment by yevhene** [comment]
@borski Maintenance is a good thing, but all maintenance this gem needs for 99% of users is two line change:
```
  s.add_runtime_dependency 'railties',       '>= 4.0'
  s.add_runtime_dependency 'activesupport',  '>= 4.0'
```
Insted of: 
```
  s.add_runtime_dependency 'railties',       '< 6.2'
  s.add_runtime_dependency 'activesupport',  '< 6.2'
```

**Comment by dominiceden** [comment]
Can we have an update please @borski ? I understand that you are trying to push things at your end but this is an incredibly basic update and a large number of people are frustrated waiting for a two line change.

**Comment by borski** [comment]
@dominiceden Sorry for the delay; as of this morning, we are good to go! Look for action today/tomorrow and activity moving forward in general, as we now have guidance on how. :)

**Comment by dominiceden** [comment]
@borski Brilliant, thanks so much! Sorry to nag, was just worried the issue had been swallowed by the corporate machine! :)

**Comment by borski** [comment]
Trust me, figuring out this problem has been a mission of mine, and if I were in your position I'd be nagging much worse, as anyone at Tinfoil can attest. :) Thanks, in kind, for being so patient while we figured this out!

**Comment by igor-drozdov** [comment]
@ebeeson Thanks for tagging a new version! Can we also release it on [rubygems](https://rubygems.org/gems/devise-two-factor/versions/3.1.0)?

**Comment by yevhene** [comment]
@borski 
```
s.add_runtime_dependency 'railties',       '< 6.2'
s.add_runtime_dependency 'activesupport',  '< 6.2'
```
Do you want us to beg you to update it every minor Rails release? :)

Just relax it please:
```
s.add_runtime_dependency 'railties',       '>= 4.0'
s.add_runtime_dependency 'activesupport',  '>= 4.0'
```

**Comment by ebeeson** [comment]
Fixed in v4.0.0.

@yevhene We're not comfortable relaxing it quite that much. If we are not able to keep up with updating and testing for future Rails releases we'll reconsider relaxing it a bit further then, but for now I think we like it where it is unless there's a compelling reason to change it.

**Comment by yevhene** [comment]
@ebeeson Please release it on RubyGems

**Comment by dominiceden** [comment]
Looks like it's now been released on RubyGems as of April 8, 2021. Thanks @ebeeson and @borski !
