### ISSUE TITLE
Publish 4.0.0?

### ISSUE THREAD

**Issue by geoffharcourt** [tinfoil/devise-two-factor#189]
Hello! 

We are thrilled to see development on this gem resume and reach version 4. Can you publish to Rubygems at some point?

Thank you for your time!

**Comment by bsedat** [comment]
Hi there! We're out of the office for a few days but we'll plan on doing a release next week.

**Comment by AshNaz87** [comment]
Any chance if this being done in the next couple of days?

**Comment by bsedat** [comment]
Published! Thank you for your patience.
