### ISSUE TITLE
Update to latest version of rotp

### ISSUE THREAD

**Issue by balasankarc** [tinfoil/devise-two-factor#38]
Hi,
I am packaging devise-two-factor for Debian, as part of GitLab packaging. Debian has rotp version 2.1.1 in the archives and it gives the following test failure with devise-two-factor. Can you please update the dependency of rotp to the latest version? It would be a great help. Thanks.

.F...................

Failures:

  1) Devise::Models::TwoFactorAuthenticatable When included in a class behaves like two_factor_authenticatable #otp_provisioning_uri should return uri with issuer option
     Failure/Error: subject.otp_provisioning_uri(account, issuer: issuer).should match(%r{otpauth://totp/#{account}\?issuer=#{issuer}&secret=\w{#{otp_secret_length}}$})
       expected "otpauth://totp/seth_predovic@watersfritsch.com?secret=5q5cxn5m5xsg7qdkhi3ga6zfmfdngeah7muhnz2sx2bcpgfxp2aqm5cp4ieeakn5ja3xzlu35n5r7rtbum3zy2bsenlpynzeryw5ecktzwbsxt5ba74yy6og6umv5f55&issuer=Tinfoil" to match /otpauth:\/\/totp\/seth_predovic@watersfritsch.com\?issuer=Tinfoil&secret=\w{128}$/
       Diff:
       @@ -1,2 +1,2 @@
       -/otpauth:\/\/totp\/seth_predovic@watersfritsch.com\?issuer=Tinfoil&secret=\w{128}$/
       +"otpauth://totp/seth_predovic@watersfritsch.com?secret=5q5cxn5m5xsg7qdkhi3ga6zfmfdngeah7muhnz2sx2bcpgfxp2aqm5cp4ieeakn5ja3xzlu35n5r7rtbum3zy2bsenlpynzeryw5ecktzwbsxt5ba74yy6og6umv5f55&issuer=Tinfoil"
       
Shared Example Group: "two_factor_authenticatable" called from ./spec/devise/models/two_factor_authenticatable_spec.rb:14
 # ./lib/devise_two_factor/spec_helpers/two_factor_authenticatable_shared_examples.rb:73:in `block (3 levels) in <top (required)>'

**Comment by ShaneWilton** [comment]
This is fixed on the master branch. I'll cut a release later today.

Thanks!

**Comment by balasankarc** [comment]
Thanks.

**Comment by ShaneWilton** [comment]
I just released v1.1.0, which resolves this issue.
