### ISSUE TITLE
sign_in_after_reset_password not available for devise < 3.5

### ISSUE THREAD

**Issue by CamJN** [tinfoil/devise-two-factor#39]
You've got to support devise 3.5+ for sign_in_after_reset_password to be available. Right now the docs are telling you to do something that doesn't work.

**Comment by ShaneWilton** [comment]
Hi @CamJN

It looks like the latest release we've built is a little bit out of date. Can you confirm that the gem works as expected if you install it from Github? Unless I'm mistaken, we've tested it fairly extensively under Devise 3.5.

**Comment by CamJN** [comment]
Yeah when I use master from github it's fine.

**Comment by ShaneWilton** [comment]
Thanks! We'll make sure to cut another release today.

**Comment by ShaneWilton** [comment]
I just released v1.1.0, which resolves this issue.
