### ISSUE TITLE
Doesn't work with Devise >= 3.5

### ISSUE THREAD

**Issue by pavel-clarityhk** [tinfoil/devise-two-factor#42]
Is it actually incompatible or just the dependencies are set that way?

```
Bundler could not find compatible versions for gem "devise":
  In snapshot (Gemfile.lock):
    devise (= 3.5.1)

  In Gemfile:
    devise-two-factor (~> 1.0.2) ruby depends on
      devise (< 3.5, >= 3.2.4) ruby
```

**Comment by bsedat** [comment]
I think you need to update your devise-two-factor version to [1.1.0](https://rubygems.org/gems/devise-two-factor/versions/1.1.0). Let me know if that works for you.

**Comment by bsedat** [comment]
Closing for now. Let me know if you're still having problems!
