### ISSUE TITLE
undefined method `bcrypt' for Devise:Module 

### ISSUE THREAD

**Issue by zlx** [tinfoil/devise-two-factor#44]
Help! 

I use this gem in my project. but I face the error when generate backup codes.

> My devise is 3.1.0 and this gem is locking 1.0.0

I find the Device.bcrypt method is defined in module [database_authenticate](https://github.com/plataformatec/devise/blob/6ed6e09bf3f8b4e32f16dfe253c89ea6bc0bf525/lib/devise/models/database_authenticatable.rb#L4-L7) which is conflict with two_factor_authenticatable.

Since some reason, I cannot upgrade my devise.
***So how can I use two_factor_authenticatable and two_factor_backupable with devise 3.1.0?***

**Comment by tadman** [comment]
`Devise.bcrypt` got moved to `Devise::Encryptor.digest` in newer versions.
