### ISSUE TITLE
Can't generate Otp_secret (ArgumentError: must specify a :key)

### ISSUE THREAD

**Issue by kiote** [tinfoil/devise-two-factor#52]
Hello and first of all thanks for this awesome gem!

I want to add it to my admin system, but faced with some troubles. My ```:two_factor_authenticatable``` named ```AdminUser```, so I followed all prescriptions you have in the readme: run generator, migration etc and now trying to make 2 factor actually work with.

```ruby
u = AdminUser.first
u.otp_secret = AdminUser.generate_otp_secret
```

With this I have an error:

```
ArgumentError: must specify a :key
from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/encryptor-1.3.0/lib/encryptor.rb:51:in `crypt'
```

I'm on Devise (3.5.2) and devise-two-factor (1.1.0)

**Comment by ShaneWilton** [comment]
Hi @kiote! Glad you're enjoying the gem :)

I can't recall the last time I've run the generator with a model named something other than `User`, so it's possible that something went wrong there. Can you confirm that your `AdminUser` model has a line that looks something like this?

```
devise :two_factor_authenticatable,
       :otp_secret_encryption_key => ENV['YOUR_ENCRYPTION_KEY_HERE']
```

It sounds like the issue is that `:otp_secret_encryption_key` is not being passed to the gem. It's also possible that you just don't have an encryption key set, in which case you'll want to make sure that the environment variable is populated with your key. If you don't have a key, you can generate one using `SecureRandom`

Let me know if this helps!

**Comment by kiote** [comment]
Thanks! I've suspected the same at first, so I've made sure that I have something in the ```ENCRYPTION_KEY``` variable. Just re-checked that. In my model:

```
devise :recoverable, :rememberable, :trackable, :validatable,
         :two_factor_authenticatable,
         otp_secret_encryption_key: ENV['ENCRYPTION_KEY']
```

and from command line:

```
echo $ENCRYPTION_KEY
some encryption key
```

so at least this seems to be in place.

**Comment by kiote** [comment]
Seems like after updating all stuff things went back to normal.

**Comment by eranbenmoha** [comment]
@kiote Could you please specify what have you done to resolve the issue? I'm facing it right now

**Comment by leevlad** [comment]
For those looking for this issue, you most likely set the OTP secret values without setting the `otp_required_for_login` field. Just reset the model and it should work fine.

**Comment by leevlad** [comment]
For those of you still running into this issue - if you're seeing this error show up in the `rails console`, it's most likely that your `spring` hasn't reloaded the environment variable. Exit out of the console, run `spring stop`, and then start the console again.

**Comment by krtschmr** [comment]
@leevlad unfortunately no.


i had OTP working, then restarted my VM and now it's breaking again

```

tim@vm:~/rails/buy_crypto$ spring stop
Spring stopped.
tim@vm:~/rails/buy_crypto$ rails c
Running via Spring preloader in process 3567
Loading development environment (Rails 5.2.2)
[1] pry(main)> u = User.first
  User Load (0.2ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<User id: 1, email: "test@test.de", created_at: "2019-01-29 03:46:34", updated_at: "2019-01-29 03:46:34", eur_balance: 12500.0, btc_balance: 0.0, xmr_balance: 0.0, google_2fa: nil, encrypted_otp_secret: nil, encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: nil, otp_secret: nil>
[2] pry(main)> u.otp_required_for_login  = true
=> true
[3] pry(main)> u.otp_secret = "6fmq4ppm2eabwuphlrlskwae"
ArgumentError: must specify a key
from /home/tim/.rvm/gems/ruby-2.6.0/gems/encryptor-3.0.0/lib/encryptor.rb:56:in `crypt'
[4] pry(main)> u.otp_secret = User.generate_otp_secret
ArgumentError: must specify a key
from /home/tim/.rvm/gems/ruby-2.6.0/gems/encryptor-3.0.0/lib/encryptor.rb:56:in `crypt'

```

**Comment by krtschmr** [comment]
@leevlad 

    devise :two_factor_authenticatable, :otp_secret_encryption_key => ENV['YOUR_ENCRYPTION_KEY_HERE']

it's also set


```

tim@vm:~/rails/buy_crypto$ export YOUR_ENCRYPTION_KEY_HERE="a3ebaae85c248da81427623959753e46b9fcb8a0d630a1e41c1dffe03596bf2ffd9701bf69fa0dd598f3c45103bdba7e956d0d3560916859884de92d1f51fe16"
tim@vm:~/rails/buy_crypto$ $YOUR_ENCRYPTION_KEY_HERE 
a3ebaae85c248da81427623959753e46b9fcb8a0d630a1e41c1dffe03596bf2ffd9701bf69fa0dd598f3c45103bdba7e956d0d3560916859884de92d1f51fe16: command not found
tim@vm:~/rails/buy_crypto$ rails c
Running via Spring preloader in process 3747
Loading development environment (Rails 5.2.2)
[1] pry(main)> u = User.first
  User Load (0.2ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<User id: 1, email: "test@test.de", created_at: "2019-01-29 03:46:34", updated_at: "2019-01-29 03:46:34", eur_balance: 12500.0, btc_balance: 0.0, xmr_balance: 0.0, google_2fa: nil, encrypted_otp_secret: nil, encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: nil, otp_secret: nil>
[2] pry(main)> u.otp_secret = "6fmq4ppm2eabwuphlrlskwae"
ArgumentError: must specify a key
from /home/tim/.rvm/gems/ruby-2.6.0/gems/encryptor-3.0.0/lib/encryptor.rb:56:in `crypt'
[3] pry(main)> 

```

**Comment by Meroal** [comment]
I noticed the issue is closed, but is there a fix for this, because I implemented this and it works in development, but no on production.  Have tested the environment variable in `rails c production` and it is passed through correctly; but the error is thrown. Any ideas?

**Comment by krtschmr** [comment]
full stacktrace? check exception in log/production.log or newrelic if you use it

**Comment by leevlad** [comment]
I would suggest dropping a `debugger` at the location of the exception thrown (e.g. in /home/tim/.rvm/gems/ruby-2.6.0/gems/encryptor-3.0.0/lib/encryptor.rb:56), and inspecting parameters passed, and repeating the process by dropping the debugger up the stack trace until you find the process (can use `Thread.current.backtrace.join("\n")` to get the stack trace).
