### ISSUE TITLE
How to check user is two-factor-authenticated or not ?

### ISSUE THREAD

**Issue by ashvushinde** [tinfoil/devise-two-factor#53]
I need to to authenticate a user is two-step authenticated or not.
As in simple devise we had a method like 
`authenticate_user!`

I need to set this in before_action filter.
Can we have similar method for two-factor-authentication?

**Comment by krtschmr** [comment]
the question isn't clear.

if a user is authenticated and 2FA is active, then he is obviously 2FA authenticated. if 2FA isn't active for him, then he is logged in default.
