### ISSUE TITLE
TwoFactorBackupable not working?

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#54]
I'm getting the following error when I try to generate the 2FA backup codes: `undefined method 'generate_otp_backup_codes' for #<Class:0x007fe485bbbf90>`

The code looks like this:
```ruby
def enable_twofactor
    self.otp_secret = User.generate_otp_secret
    self.otp_backup_codes = User.generate_otp_backup_codes
    self.save
end
```

Generating the `otp_secret` works, but not the backup codes. I've added the db migration and run `rake db:migrate`, added the strategy to the devise initializer, followed the instructions and re-read them over and over.

Any ideas as to why this might be happening?

**Comment by bsedat** [comment]
Is `:two_factor_backupable` in the list of devise modules in your model's call to set up devise?

**Comment by connorshea** [comment]
Yeah, this is in our `user.rb` model:

```ruby
devise :two_factor_backupable,
    otp_backup_code_length: 16,
    otp_number_of_backup_codes: 5
```

**Comment by connorshea** [comment]
Any other ideas?

**Comment by bsedat** [comment]
Sorry for the wait. I think the issue is that the method is actually `generate_otp_backup_codes!`. We should make that clearer in the README (pull requests welcome! :smile:)

**Comment by connorshea** [comment]
Turns out we needed to change that *and* change the second line to `self.generate_otp_backup_codes!`. Thanks for the help :)

**Comment by bsedat** [comment]
Ah yeah, it acts on the User instance and invalidates all current OTP backup codes. Glad you got it working now!
