### ISSUE TITLE
Require password entry before allowing the user to disable 2FA on their account

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#55]
This is what Slack, Stripe, and others do to prevent other people with access to your computer from disabling Two-Factor Auth on your account. I realize it's not likely to stop people if they have physical access, but why not add it?

**Comment by f3ndot** [comment]
This is a valid practice, but you can do it on your end on the controller actions that update your model.

```ruby
def update
  fail SecurityError, 'password required' unless current_resource_owner.valid_password?(params[:password])
  # ...
end
```

**Comment by bsedat** [comment]
I think this may be out of scope for the gem. Thanks @f3ndot for the workaround!
