### ISSUE TITLE
How should I integrate Devise two factor authentication with custom sessions controller?

### ISSUE THREAD

**Issue by ashvushinde** [tinfoil/devise-two-factor#61]
I integrated the Houdini two factor authentication with existing rails application.  
First I doesn't have any custom sessions_controller then the <b><i>two_factor_authentication</i></b> is working fine.  
But whereas I written custom create action in Sessions Controller then it doesn't authenticated by <b><i>two_factor_authentication</i></b>.

Here is the custom code for create action of Sessions Controller.

      if status_response.nil?
        render :file => 'public/api_not_found.html', :status => :not_found, :layout => false
      else
        if status_response['code'].to_i == 1
          signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
          flash[:alert] = 'Invalid Email ID or password.'
          yield if block_given?
          respond_to_on_destroy
        else
          self.resource = warden.authenticate!(auth_options)
          set_flash_message(:notice, :signed_in) if is_flashing_format?
          sign_in(resource_name, resource)
          yield resource if block_given?
          respond_with resource, location: after_sign_in_path_for(resource)
        end
      end

Model code of user.rb:

      devise :two_factor_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, password_length: 8..30
      has_one_time_password

      def send_two_factor_authentication_code
        puts ">>>>>>>>>>>>>>> otp_secret_key: #{otp_secret_key}, otp_code: #{otp_code}"
      end

I know if we are customizing the create action of Sessions Controller then we should call the <b><i>two_factor_authentication</i></b>. I tried to invoke this in controller but it throws an error.

So my question how should i integrate the <b><i>two_factor_authentication</i></b> with custom create action of Session Controller?

**Comment by kiote** [comment]
I'm on same page now, so if you have any answer, please, share!

**Comment by connorshea** [comment]
[GitLab does this and is fully open source](https://gitlab.com/gitlab-org/gitlab-ce/tree/master). I unfortunately don't know the exact location of the relevant code, but you can look through the repository and try to find it.

**Comment by connorshea** [comment]
Here's [the Merge Request](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/474) that introduced it, as well.

**Comment by kiote** [comment]
oh, thanks @connorshea, really!

I was thinking that I just need something equals to github have, but didn't remember about gitlab :tropical_fish: 

Thanks :+1:

**Comment by bsedat** [comment]
Glad you found an example! Thank you for the guidance @connorshea!

**Comment by AndrewRayCode** [comment]
This ticket is confusing. The first question is asking about a different gem, https://github.com/Houdini/two_factor_authentication, and using `two_factor_authenticatable`, but I don't think anyone noticed?

**Comment by connorshea** [comment]
@AndrewRayCode whoops!

**Comment by krtschmr** [comment]
@AndrewRayCode  happened to me like crazy. i tried both gems and for each i used the other gem doc and ragedquitted as nothing worked, created stupid issues and stuff. lololol
