### ISSUE TITLE
Symmetrically encrypt backup codes with user password & attr_encrypted

### ISSUE THREAD

**Issue by f3ndot** [tinfoil/devise-two-factor#64]
I've seen a lot of vendors use the pattern of re-displaying the users' backup codes many times (usually after user re-enters their password for verification purposes). And even showing which codes have been burned. Even Google has adopted this pattern.

Unless I'm mistaken, because TwoFactorBackupable uses `Devise::Encryptor#digest` the codes can only be displayed once and no more. While this is wonderfully secure, I feel like the hit to the user is such that it warrants re-evaluation.

I propose that `attr_encrypted` is leveraged to safely keep the backup codes encrypted at rest but can be, when combined with a supplied password, be displayed the user on subsequent requests in case they need to reprint or rewrite them down.

[`attr_encrypted` supports methods as a key](https://github.com/attr-encrypted/attr_encrypted#symbols-representing-instance-methods-as-keys) so associating it with a user's password is doable. 

What do you think?

**Comment by f3ndot** [comment]
Added in https://github.com/tinfoil/devise-two-factor/pull/73 and https://github.com/tinfoil/devise-two-factor/pull/76

**Comment by melbreaker** [comment]
@f3ndot Can you give an example of how to use attr_encrypted with otp_back_codes so that it can be displayed to user anytime?

**Comment by f3ndot** [comment]
@melbreaker should be as simple as:

```ruby
Class User

 # ...

  attribute :otp_backup_codes # Needed for Rails 5. Remove once attr_encrypted releases their fix. See attr-encrypted/attr_encrypted#263
  attr_encrypted :otp_backup_codes, key: Rails.application.secrets.two_factor_auth[:otp_encryption_key]

 # ...

end
```

Note you probably don't want to show the backup codes to the user without first prompting them for a password.
