### ISSUE TITLE
Allow attr_encrypted 2.x

### ISSUE THREAD

**Issue by istana** [tinfoil/devise-two-factor#69]
attr_encrypted 2.0 introduced more secure default settings (aes-256-gcm) and a new mode per_attribute_iv

**Comment by connorshea** [comment]
I [attempted to do this](https://github.com/tinfoil/devise-two-factor/pull/70) in my Pull Request that added Devise 4.0.0, but I ran into an issue. With 2.0.0 the test suite doesn't work and throws this error:

```
Connors-MacBook-Pro:devise-two-factor connor$ bundle exec rake
/Users/connor/.rvm/rubies/ruby-2.3.0/bin/ruby -I/Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib:/Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-support-3.4.1/lib /Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec spec/devise/models/two_factor_authenticatable_spec.rb spec/devise/models/two_factor_backupable_spec.rb
/Users/connor/Programming/devise-two-factor/lib/devise_two_factor/models/two_factor_authenticatable.rb:12:in `block in <module:TwoFactorAuthenticatable>': undefined method `attr_encrypted?' for TwoFactorAuthenticatableDouble:Class (NoMethodError)
```

I [opened an issue](https://github.com/attr-encrypted/attr_encrypted/issues/198), but apparently the `attr_encrypted?` method still exists. So there must be some problem with the way we're using it.

For future note, whenever someone goes about adding support for 2.x :)
