### ISSUE TITLE
Change value of otp_allowed_drift

### ISSUE THREAD

**Issue by kiote** [tinfoil/devise-two-factor#71]
Hi! I'm trying to change the value of `otp_allowed_drift`, but have no success with that. Could you please help me here?

What I've tried already:

```ruby
# config/initializers/devise.rb
Devise.setup do |config|
  config.otp_allowed_drift = 1800
end
```

and

```ruby
# config/initializers/devise.rb
Devise.otp_allowed_drift = 1800
Devise.setup do |config|
  ...
end
```

With the second attempt the value of `otp_allowed_drift` had been changed, but my otp codes still changes like once in 30 seconds (default value), not once in 30 minutes as I expect to.

**Comment by bsedat** [comment]
`otp_allowed_drift` specifies the amount of time an older OTP code would be considered valid [[1]](https://github.com/tinfoil/devise-two-factor/blob/e59657522142bb89df95b9f4862122876a566d04/lib/devise_two_factor/models/two_factor_authenticatable.rb#L28). I believe new codes will still be regenerated every 30 seconds no matter what as recommended in the [OTP RFC](https://tools.ietf.org/html/rfc6238#section-5.2).

**Comment by bsedat** [comment]
The [rotp gem](https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L10) seems to allow this to be modified. You could probably modify [here](https://github.com/tinfoil/devise-two-factor/blob/e59657522142bb89df95b9f4862122876a566d04/lib/devise_two_factor/models/two_factor_authenticatable.rb#L34) to consume a new devise option if you wanted to.

**Comment by kiote** [comment]
> specifies the amount of time an older OTP code would be considered valid

Hm, that seems like what I actually need, but I probably verify code from user wrong way then. I do a check `user.current_otp == otp_attempt` where `otp_attempt` is a code given by user.

**Comment by bsedat** [comment]
You'll want to use our provided method [user.validate_and_consume_otp!](https://github.com/tinfoil/devise-two-factor/blob/e59657522142bb89df95b9f4862122876a566d04/lib/devise_two_factor/models/two_factor_authenticatable.rb#L23).

**Comment by kiote** [comment]
ah, that seems like a great fit, thanks a lot!
