### ISSUE TITLE
Previously consumed OTP is considered valid after drift period has passed

### ISSUE THREAD

**Issue by monfresh** [tinfoil/devise-two-factor#80]
RFC 6238 says that once an OTP is used, it cannot ever be used again.

The tests here are not properly testing the scenario where an OTP is consumed, then the user waits an amount between the drift period and twice the drift period, then tries entering the OTP again. The expected behavior is that the OTP should not be valid, but it is. 

The problem with the tests is that they are freezing `Time.current`, but because `current_otp_timestep` depends on the current time, it must not be frozen. Instead `Timecop.travel` must be used to advance in time.

Here is a failing spec:

``` ruby
describe '#validate_and_consume_otp!' do
  let(:otp_secret) { '2z6hxkdwi3uvrnpn' }

  before :each do
    subject.otp_secret = otp_secret
  end

  after :each do
    Timecop.return
  end

  context 'with a stored consumed_timestep' do
    context 'given a previously correct OTP' do
      it 'fails to validate' do
        consumed_otp = ROTP::TOTP.new(otp_secret).at(Time.now)
        subject.validate_and_consume_otp!(consumed_otp)

        amount_to_travel = (subject.class.otp_allowed_drift).seconds
        Timecop.travel(amount_to_travel)

        expect(subject.validate_and_consume_otp!(consumed_otp)).to be false
      end
    end
  end
end
```

**Comment by monfresh** [comment]
I updated my comment. I had pasted in the wrong code initially.

If you play around with the `time_to_travel` value, you'll see that when the amount of time to travel is equal to the drift period or between the drift period and twice the drift period, the test fails, but if you advance 60 seconds, then the test passes.

**Comment by monfresh** [comment]
Here is an interesting discussion on this subject: https://github.com/mdp/rotp/issues/44

**Comment by monfresh** [comment]
The ROTP gem has now implemented this via the `verify_with_drift_and_prior ` method. See: https://github.com/mdp/rotp#preventing-reuse-of-time-based-otps

Would it make sense for this gem to use that functionality as opposed to your own implementation?

**Comment by ShaneWilton** [comment]
I think that'd be a worthwhile change to make. Thanks for pointing it out!

If you were to open a pull request, I'd be happy to review it.
