### ISSUE TITLE
NoMethodError: undefined method `validate_and_consume_otp!' 

### ISSUE THREAD

**Issue by acegilz** [tinfoil/devise-two-factor#82]
```
class User < ActiveRecord::Base
  devise :rememberable, :trackable, :lockable,
         :session_limitable, :two_factor_authenticatable,
         :otp_secret_encryption_key => ENV['TWO_FACTOR_SECRET']
  # ...
end
```

and then

```
2.1.1 :001 >user = user.first
2.1.1 :002 > user.validate_and_consume_otp!('x','x')
NoMethodError: undefined method `validate_and_consume_otp!' for #<User:0x00000006402378>
```

**Comment by bsedat** [comment]
Do you have any other information about your environment you are running this in (Rails version, other devise-related gems, etc.)? It seems to be available in the [demo app](https://github.com/tinfoil/devise-two-factor/tree/master/demo) when I tried it just now.

**Comment by acegilz** [comment]
what exactly would I need to just put ## two_factor_authenticatable integrated with my users model?

I tried everything but calling user. validate_and_consume_otp! will always return nomethod error, I think that with just the gem installed and thos lines on user model it would be enought.

I'm going crazy with this one

**Comment by bsedat** [comment]
What version of devise-two-factor are you using? v1.0.0 through v.1.1.0 use `#valid_otp?`. It changed to `validate_and_consume_otp!` in v2.0.0.

**Comment by acegilz** [comment]
im on 1.0.0!

**Comment by acegilz** [comment]
thanks! @bsedat !!!

**Comment by lahiruj** [comment]
Thanks @bsedat
