### ISSUE TITLE
Upgrade guide for devise-two-factor with attr_encrypted 3.x doesn't work

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#91]
Assuming the user has followed the `README.md` instructions for past versions of devise-two-factor, they should have something like this in their User model:

``` ruby
devise :two_factor_authenticatable,
  :otp_secret_encryption_key => ENV['YOUR_ENCRYPTION_KEY_HERE']
```

The suggestion in the `UPGRADING.md` is to replace the above with the following:

``` ruby
attr_encrypted :otp_secret,
  :key       => self.otp_secret_encryption_key,
  :mode      => :per_attribute_iv_and_salt,
  :algorithm => 'aes-256-cbc'

devise :two_factor_authenticatable,
  :otp_secret_encryption_key => ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY']
```

The problem with this is that `otp_secret_encryption_key` isn't an attribute of the model, so it throws an error.

I had to change the code to the following for it to work with devise-two-factor (current `devise-4` branch), Devise 4, and attr_encrypted/encryptor 3.0:

``` ruby
  attr_encrypted :otp_secret,
    :key       => ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY'],
    :mode      => :per_attribute_iv_and_salt,
    :algorithm => 'aes-256-cbc'

  devise :two_factor_authenticatable,
         :otp_secret_encryption_key => ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY']
```

The error was initially:

```
NoMethodError - undefined method `otp_secret_encryption_key' for #<Class:0x007fd612c5d880>:
```

The error I got after changing `self.otp_secret_encryption_key` to `:otp_secret_encryption_key` was:

```
NoMethodError - undefined method `bytesize' for :otp_secret_encryption_key:Symbol:
```

After adding `:insecure_mode => true` it became:

```
TypeError - no implicit conversion of Symbol into String:
```

Only when I used the environment variable directly did it work. I should also note that we don't actually use an environment variable, but instead use `File.read(Rails.root.join('.secret')).chomp`. I don't think that changes anything, but I thought it was worth mentioning just in case.

**Comment by connorshea** [comment]
The guide should be changed to:
```
attr_encrypted :otp_secret,
  :key       => ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY'],
  :mode      => :per_attribute_iv_and_salt,
  :algorithm => 'aes-256-cbc'

devise :two_factor_authenticatable,
  :otp_secret_encryption_key => ENV['DEVISE_TWO_FACTOR_ENCRYPTION_KEY']
```

I can open a PR for this if you'd like. Will the 3.0.0 release will be coming on RubyGems this week?

**Comment by P9GIT** [comment]
I'm rather confused about this part of the guide.

According to the attr_encrypted changelog (https://github.com/attr-encrypted/attr_encrypted/blob/master/CHANGELOG.md), the option "per_attribute_iv_and_salt" is removed in version three:

"2.0.0
...
Deprecated: :single_iv_and_salt and :per_attribute_iv_and_salt modes are deprecated and will be removed in the next major release. (@saghaulor)"

Your gemspec accepts attr_encryped version 3 (which is what we get after devise-two-factor was bumped to 2.2.x) so this seems to contradict the guide advising to use the deprecated option.

Besides, have you any guidance on how to migrate encrypted data using devise-two-factor(2.1.0)/attr_encrypted(1.4.0) to the latest versions?
Using the guide above seems to postpone the problem rather than solving it...
Any pointers?

Best regards,
Thomas Balsløv.

**Comment by connorshea** [comment]
@P9GIT you'd have to take the application offline to decrypt the encrypted information, then re-encrypt it using the new encryption algorithm that attr_encrypted defaults to (`aes-128-gcm`) as well as the new mode (and a new encryption key if yours wasn't long enough before). `aes-256-cbc` isn't insecure, so you can get away with using it for probably a pretty long time, the problem is that if you want to switch mode or key you'll have to re-encrypt everything anyway. This will eventually block you from upgrading to attr_encrypted 4.0 if/when it comes out if you don't do it now.

As for why my suggestions didn't work, I'm guessing you didn't use a key that was of sufficient length, so you have to use `insecure_mode` or attr_encrypted won't be happy. In my case I had a key that was long enough.

**Comment by P9GIT** [comment]
Hi! @connorshea
Thanks a lot for your reply, that helps a lot!

**Comment by connorshea** [comment]
@P9GIT no problem, I've been researching this stuff for GitLab anyway, so I have lots of information hoarded :)
