### ISSUE TITLE
Release 3.0.0 on RubyGems

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#94]
Not to be a bother, but I'd like to upgrade GitLab to Devise 4, and this is the only thing blocking that upgrade.

Is there anything left to do or is it ready for release?

**Comment by bsedat** [comment]
Done. :smile:
Thank you again for helping push this forward. Let us know how the upgrade goes!

**Comment by connorshea** [comment]
That was fast, thanks! Will do :)
